[package]
name = "docs_to_markdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2runes = "1.0.1"
regex = "1.7.0"
reqwest = {version = "0.11.13", features = ["blocking"]}
select = "0.6.0"
